- name: Demo on variables
  hosts: localhost
  vars_prompt:
  - name: "friend_name"
    prompt: please enter your friend name
    ##private: no
  tasks:
    - name: Printing the variables
      debug:
        msg: "Bestie={{friend_name}}"