- name: Demo on Installing multiple packages
  hosts: localhost
  become: yes
  tasks:
    - name: Installing the packages
      yum:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
        - { name: httpd , state: latest }
        - { name: httpd-devel , state: present }
        - { name: gcc , state: absent }