- name: checking the file exits or not
  hosts: localhost
  tasks:
    - name: get the statistics of the file
      stat:
        path: /home/devopsuser/kutti
      register: st
    - name: printing the actual output
      debug:
        msg: "{{st}}"
    - name: get the actual output of the file
      set_fact:
        file_exists: "{{st.stat.exists}}"
    - name: printing the actual output
      debug:
        msg: "{{file_exists}}"
    - name: printing the actual output
      debug:
        msg: "file is existsing"
      when: file_exists == true
    - name: printing if file not exists output
      debug:
        msg: "file is does not exists"
      when: file_exists == false
             